{{- if or .Values.cvm.enabled .Values.cvm.grok_compute.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  {{- with .Values.cvm.grok_compute.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ include "base.defaultLabels" . | nindent 4 }}
  name: {{ include "base.fullname" . }}-{{ .Values.cvm.grok_compute.container.name }}
spec:
  replicas: {{ .Values.cvm.grok_compute.replicas }}
  revisionHistoryLimit: 10
  selector:
    {{- with .Values.cvm.grok_compute.labels }}
    matchLabels:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- include "base.selectorLabels" . | nindent 8 }}
  strategy:
    type: {{ .Values.cvm.grok_compute.strategy_type}}
  template:
    metadata:
      {{- with .Values.cvm.grok_compute.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.cvm.grok_compute.container.image }}:{{ .Values.cvm.grok_compute.container.tag }}
          imagePullPolicy: {{ .Values.cvm.grok_compute.container.imagePullPolicy }}
          name: {{ .Values.cvm.grok_compute.container.name }}
          {{- with .Values.cvm.grok_compute.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cvm.grok_compute.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cvm.grok_compute.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.cvm.grok_compute.container.port }}
      restartPolicy: {{ .Values.cvm.grok_compute.restartPolicy }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cvm.grok_compute.container.name }}
  labels:
{{ include "base.defaultLabels" . | nindent 4 }}
spec:
  type: {{ .Values.cvm.grok_compute.service.type }}
  ports:
    - port: {{ .Values.cvm.grok_compute.container.port  }}
      targetPort: {{ .Values.cvm.grok_compute.container.port }}
      protocol: TCP
      name: http
  {{- with .Values.cvm.grok_compute.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- include "base.selectorLabels" . | nindent 4 }}

{{- end }}