{{- if or .Values.cvm.enabled .Values.cvm.jkg.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}-{{ .Values.cvm.jkg.container.name }}-{{ .Values.cvm.jkg.container.tag 
  namespace: {{ .Release.Namespace }}
  {{- with .Values.cvm.jkg.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ include "base.defaultLabels" . | nindent 4 }} 
  
spec:
  replicas: {{ .Values.cvm.jkg.replicas }}
  selector:
    {{- with .Values.cvm.jkg.labels }}
    matchLabels:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- include "base.selectorLabels" . | nindent 8 }}
  strategy:
    type: {{ .Values.cvm.jkg.strategy_type}}
  template:
    metadata:
      {{- with .Values.cvm.jkg.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.cvm.jkg.container.image }}:{{ .Values.cvm.jkg.container.tag }}
          imagePullPolicy: {{ .Values.cvm.jkg.container.imagePullPolicy }}
          name: {{ .Values.cvm.jkg.container.name }}
          {{- with .Values.cvm.jkg.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cvm.jkg.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cvm.jkg.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-jkg-grok-parameters-configmap  
          ports:
            - containerPort: {{ .Values.cvm.jkg.container.ports.jupyter.port }}
            - containerPort: {{ .Values.cvm.jkg.container.ports.helper.port }}
      restartPolicy: {{ .Values.cvm.jkg.restartPolicy }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cvm.jkg.container.name }}
  labels:
{{ include "base.defaultLabels" . | nindent 4 }}
spec:
  type: {{ .Values.cvm.jkg.service.type }}
  ports:
    - port: {{ .Values.cvm.jkg.container.ports.jupyter.port  }}
      targetPort: {{ .Values.cvm.jkg.container.ports.jupyter.port }}
      protocol: TCP
      name: {{ .Values.cvm.jkg.container.ports.jupyter.name }} 
    - port: {{ .Values.cvm.jkg.container.ports.helper.port  }}
      targetPort: {{ .Values.cvm.jkg.container.ports.helper.port }}
      protocol: TCP
      name: {{ .Values.cvm.jkg.container.ports.helper.name }} 
  {{- with .Values.cvm.jkg.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- include "base.selectorLabels" . | nindent 4 }}
 
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jkg-grok-parameters-configmap
data: 
  {{ $len := sub (len .Values.cvm.jkg.grok_parameters) 1 }}
  {{ $count := 1 }}
  {{ $list := list }}
  GROK_PARAMETERS: |-
    {
      {{ range $key, $value := .Values.cvm.jkg.grok_parameters }}
      {{ if le $count $len }}
        {{- if kindIs "string" $value }}
          {{- $key | quote | indent 2 }}: {{ $value | quote }},
        {{- else }}
          {{- if eq $key "capabilities" }}
            {{- $lastIndex := sub (len $value) 1 }}
            {{- range $index, $list_value := $value }}
              {{- $list = append $list (printf "%q" $list_value) }}
              {{- if ne $index $lastIndex }}
                {{- $list = append $list "," }}
              {{- end }}
            {{- end }}
            {{- $key | quote | indent 2 }}: {{ $list }},
          {{- else }}
            {{- $key | quote | indent 2 }}: {{ $value }},
          {{- end }}
        {{- end }}
        {{- $count = add $count 1 }}
      {{- else }}
        {{- if kindIs "string" $value }}
          {{- $key | quote | indent 2 }}: {{ $value | quote }}
        {{- else }}
          {{- if eq $key "capabilities" }}
            {{- $lastIndex := sub (len $value) 1 }}
            {{- range $index, $list_value := $value }}
              {{- $list = append $list (printf "%q" $list_value) }}
              {{- if ne $index $lastIndex }}
                {{- $list = append $list "," }}
              {{- end }}
            {{- end }}
            {{- $key | quote | indent 2 }}: {{ $list }}
          {{- else }}
            {{- $key | quote | indent 2 }}: {{ $value }}
          {{- end }}
        {{- end }}
        {{- $count = add $count 1 }}
      {{- end }}
      {{- end }}
      }
{{- end }}