# version: '3'
services:
  db:
    image: postgres:12
    container_name: db
    restart: always
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: postgres
      POSTGRES_USER: root
    # networks:
      # - white-label
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data