{{- if .Values.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}
  labels:
{{ include "base.defaultLabels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.container.port  }}
      targetPort: {{ .Values.container.port }}
      nodePort: 30000
      protocol: TCP

{{/*  type: {{ .Values.service.type }}*/}}
{{/*  ports:*/}}
{{/*    - port: {{ .Values.container.port  }}*/}}
{{/*      targetPort: {{ .Values.container.port }}*/}}
{{/*      protocol: TCP*/}}
{{/*      name: http*/}}
  {{- with .Values.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- include "base.selectorLabels" . | nindent 4 }}



{{- end }}
