{{- if .Values.core.enabled -}}
{{- if .Values.cvm.jkg.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-configmap
data:
{{- range $key, $value := .Values.core.database.configmap }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
{{- end }}