{{- if or .Values.cvm.jkg.enabled .Values.global.core.enabled -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "base.fullname" . }}-db
  {{- with .Values.datagrok_test.database.statefulset.pod.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ include "base.defaultLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.datagrok_test.database.statefulset.replicas }}
  serviceName: {{ include "base.fullname" . }}-db
  replicas: {{ .Values.datagrok_test.database.statefulset.replicas }}
  minReadySeconds: {{ .Values.datagrok_test.database.statefulset.minReadySeconds }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
  updateStrategy: 
    type: "RollingUpdate"
  selector:
    {{- with .Values.datagrok_test.database.statefulset.pod.labels }}
    matchLabels:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      {{ include "base.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      {{- with .Values.datagrok_test.database.statefulset.pod.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ include "base.selectorLabels" . | nindent 8 }}
      {{- with .Values.datagrok_test.database.statefulset.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
    spec:
      terminationGracePeriodSeconds: {{ .Values.datagrok_test.database.statefulset.pod.terminationGracePeriodSeconds }}
      containers:
        - name: {{ include "base.fullname" . }}-{{ .Values.datagrok_test.database.statefulset.pod.container.name }}
          image: {{ .Values.datagrok_test.database.statefulset.pod.container.image }}:{{ .Values.datagrok_test.database.statefulset.pod.container.tag }}
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: {{ .Values.datagrok_test.database.statefulset.pod.container.port  }}
            protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-db-configmap
          volumeMounts:
            - mountPath: {{ .Values.datagrok_test.database.statefulset.pod.container.volume.path }}
              name: {{ .Values.datagrok_test.database.volumeClaimTemplates.name }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.datagrok_test.database.volumeClaimTemplates.name }}
      spec:
        accessModes: {{ .Values.datagrok_test.database.volumeClaimTemplates.accessMode }}
        storageClassName: {{ .Values.datagrok_test.database.volumeClaimTemplates.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.datagrok_test.database.volumeClaimTemplates.storage }}
{{- end }}