apiVersion: v1
entries:
  datagrok-test:
  - apiVersion: v2
    appVersion: 1.19.x
    created: "2024-08-22T11:12:32.670246004Z"
    dependencies:
    - name: datagrok_grok_connect_test
      repository: '@datagrok-test'
      version: 0.4.0
    - name: datagrok_jkg-test
      repository: '@datagrok-test'
      version: 0.1.0
    - name: datagrok_jupyter_notebook_test
      repository: '@datagrok-test'
      version: 0.1.0
    - name: datagrok_grok_spawner_test
      repository: '@datagrok-test'
      version: 0.1.0
    description: A Helm chart for Kubernetes
    digest: 78cc950aa81bf26a725e0704c9895c3f58e77b16b7778227b699650caa9e62eb
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok-test
    type: application
    urls:
    - datagrok-test-1.0.1.tgz
    version: 1.0.1
  datagrok_grok_connect_test:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.671495107Z"
    description: A Helm chart for Kubernetes
    digest: fb6c8bd61449fe006cd43a32b8e5484fb80b618f54c0c2f463ba36e54cda8ed9
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_connect_test
    type: application
    urls:
    - datagrok_grok_connect_test-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.671269606Z"
    description: A Helm chart for Kubernetes
    digest: 7211cd290584cc718e6386f1af8e0ae8b14771c2e3b7dcfc5e7720b46bc7c257
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_connect_test
    type: application
    urls:
    - datagrok_grok_connect_test-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.671037883Z"
    description: A Helm chart for Kubernetes
    digest: aca4d818ac0cbf5c28fd2feaefd0d47171a03b04d2c739b39c8bc403334aae43
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_connect_test
    type: application
    urls:
    - datagrok_grok_connect_test-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.670758551Z"
    description: A Helm chart for Kubernetes
    digest: e889c2255a451c1d77e20e3f104c72ee1c4b689593f8598099780cacb9aab837
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_connect_test
    type: application
    urls:
    - datagrok_grok_connect_test-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.67050613Z"
    description: A Helm chart for Kubernetes
    digest: 80b1c45eec4ba5824d8ae5ceae30f58b209badc6ea1a67decb82c492f7376166
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_connect_test
    type: application
    urls:
    - datagrok_grok_connect_test-0.1.0.tgz
    version: 0.1.0
  datagrok_grok_spawner_test:
  - apiVersion: v2
    appVersion: 1.19.0
    created: "2024-08-22T11:12:32.680503039Z"
    dependencies:
    - name: minio
      repository: ""
      version: 14.6.22
    description: A Helm chart for Kubernetes
    digest: c706a1bf5478d244d773c004b2cc3cfbe4fe6c5447241bd03cf58e89f1829439
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_spawner_test
    type: application
    urls:
    - datagrok_grok_spawner_test-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.19.0
    created: "2024-08-22T11:12:32.67637474Z"
    dependencies:
    - name: minio
      repository: ""
      version: 14.6.22
    description: A Helm chart for Kubernetes
    digest: 95d5a4f015d02d769c17ca34cc08fd3e271d22cd6d211cbfe72a7f0006d34b58
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_spawner_test
    type: application
    urls:
    - datagrok_grok_spawner_test-0.1.0.tgz
    version: 0.1.0
  datagrok_jkg-test:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.681069277Z"
    description: A Helm chart for Kubernetes
    digest: 9e7666d28ce94c7c1ef4522cadd2e92a0df0080548bb541db97e0eb28052e862
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jkg-test
    type: application
    urls:
    - datagrok_jkg-test-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.680784945Z"
    description: A Helm chart for Kubernetes
    digest: 119bd85c471bd12a6b7a1b0ff806c2fe6c7f47a9a1f0962ba4a99584896b8674
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jkg-test
    type: application
    urls:
    - datagrok_jkg-test-0.1.0.tgz
    version: 0.1.0
  datagrok_jupyter_notebook_test:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.68192265Z"
    description: A Helm chart for Kubernetes
    digest: f1bbdd30461dec1cfbe49b367ecf52ffe8b70f9f85e96932a6d93c5c77bb21a2
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jupyter_notebook_test
    type: application
    urls:
    - datagrok_jupyter_notebook_test-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T11:12:32.681297653Z"
    description: A Helm chart for Kubernetes
    digest: 09a33d494d08d24e57e17f2ff75365dd09c2221a91e9652d809dcc07991707b5
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jupyter_notebook_test
    type: application
    urls:
    - datagrok_jupyter_notebook_test-0.1.0.tgz
    version: 0.1.0
generated: "2024-08-22T11:12:32.663265879Z"
