apiVersion: v1
entries:
  datagrok_grok_connect_test:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T10:54:10.782456833Z"
    description: A Helm chart for Kubernetes
    digest: fb6c8bd61449fe006cd43a32b8e5484fb80b618f54c0c2f463ba36e54cda8ed9
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_connect_test
    type: application
    urls:
    - datagrok_grok_connect_test-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T10:54:10.782202588Z"
    description: A Helm chart for Kubernetes
    digest: 80b1c45eec4ba5824d8ae5ceae30f58b209badc6ea1a67decb82c492f7376166
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_connect_test
    type: application
    urls:
    - datagrok_grok_connect_test-0.1.0.tgz
    version: 0.1.0
  datagrok_grok_spawner_test:
  - apiVersion: v2
    appVersion: 1.19.0
    created: "2024-08-22T10:54:10.7921766Z"
    dependencies:
    - name: minio
      repository: ""
      version: 14.6.22
    description: A Helm chart for Kubernetes
    digest: c706a1bf5478d244d773c004b2cc3cfbe4fe6c5447241bd03cf58e89f1829439
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_spawner_test
    type: application
    urls:
    - datagrok_grok_spawner_test-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.19.0
    created: "2024-08-22T10:54:10.787645283Z"
    dependencies:
    - name: minio
      repository: ""
      version: 14.6.22
    description: A Helm chart for Kubernetes
    digest: 95d5a4f015d02d769c17ca34cc08fd3e271d22cd6d211cbfe72a7f0006d34b58
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_spawner_test
    type: application
    urls:
    - datagrok_grok_spawner_test-0.1.0.tgz
    version: 0.1.0
  datagrok_jkg-test:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T10:54:10.792747306Z"
    description: A Helm chart for Kubernetes
    digest: 9e7666d28ce94c7c1ef4522cadd2e92a0df0080548bb541db97e0eb28052e862
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jkg-test
    type: application
    urls:
    - datagrok_jkg-test-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T10:54:10.792464177Z"
    description: A Helm chart for Kubernetes
    digest: 119bd85c471bd12a6b7a1b0ff806c2fe6c7f47a9a1f0962ba4a99584896b8674
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jkg-test
    type: application
    urls:
    - datagrok_jkg-test-0.1.0.tgz
    version: 0.1.0
  datagrok_jupyter_notebook_test:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T10:54:10.793213206Z"
    description: A Helm chart for Kubernetes
    digest: f1bbdd30461dec1cfbe49b367ecf52ffe8b70f9f85e96932a6d93c5c77bb21a2
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jupyter_notebook_test
    type: application
    urls:
    - datagrok_jupyter_notebook_test-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-22T10:54:10.792982305Z"
    description: A Helm chart for Kubernetes
    digest: 09a33d494d08d24e57e17f2ff75365dd09c2221a91e9652d809dcc07991707b5
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jupyter_notebook_test
    type: application
    urls:
    - datagrok_jupyter_notebook_test-0.1.0.tgz
    version: 0.1.0
generated: "2024-08-22T10:54:10.781675002Z"
