{{- if .Values.enabled -}}

{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "base.defaultLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{ $subdomain := .Values.container.tag | replace "." "-" }}
    {{- range .Values.ingress.hosts }}
    - host: "{{ $subdomain }}.{{ .host }}"
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .backend.serviceName }}
                port:
                  name: {{ .backend.servicePort }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}