name: Helm Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'base/**'

permissions:
  contents: write
  id-token: write

jobs:
  helm-lint-deploy-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Publish
        run: |
          touch test-123
          git add .
          git commit -m "Bump version helm charts"
          git push 
      

  helm-lint-deploy-datagrok:
    runs-on: ubuntu-latest
    needs: [helm-lint-deploy-packages]
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Git pull changes
        run: git pull
      - name: Add helm repo
        run: helm repo add datagrok-test https://vhlushchen.github.io/slack-notif/charts/
      - uses: dorny/paths-filter@v3
        id:  chart_changes
        with:
          filters: |
            datagrok:
              - 'base/datagrok-helm-chart/**'
            datagrok_publish:
              - 'base/datagrok-helm-chart/Chart.yaml'
      - name: datagrok lint
        if: steps.chart_changes.outputs.datagrok == 'true'
        run: helm lint ./base/datagrok-helm-chart

      - name: datagrok dependency update
        if: steps.chart_changes.outputs.datagrok_publish == 'true'
        working-directory: ./base/datagrok-helm-chart
        run: |
          sleep 30
          helm dependency list
          helm repo update
          helm dependency update --debug
      - name: helm package
        run: helm package ./base/datagrok-helm-chart -d charts/
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Publish
        run: |
          helm repo index charts
          git add .
          git commit -m "Bump version datagrok helm charts"
          git push 
