name: Test Bash

on:
  push:
    branches:
      - master

jobs:
  test-start-update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: datagrok lint
        run: helm lint datagrok-helm-chart    
      
      