name: Helm lint

on:
  push:
    branches:
      - master

jobs:
  test-start-update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: datagrok lint
        run: helm lint datagrok-helm-chart
      - name: grok_connect lint
        run: helm lint datagrok_grok_connect
      - name: helm lint h2o
        run: helm lint datagrok_h2o
      - name: helm lint jkg
        run: helm lint datagrok_jkg
      - name: helm lint jupyter_notebook
        run: helm lint datagrok_jupyter_notebook       
      
      