name: Helm lint

on:
  push:
    branches:
      - master

jobs:
  test-start-update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id:  chart_changes
        with:
          filters: |
            grok_connect:
              - 'datagrok_grok_connect/**'
            h2o:
              - 'datagrok_h2o/**'
            jkg:
              - 'datagrok_jkg/**'
            jn:
              - 'datagrok_jupyter_notebook/**'
            datagrok:
              - 'datagrok-helm-chart/**'
      - name: datagrok lint
        if: steps.chart_changes.outputs.datagrok == 'true'
        run: helm lint datagrok-helm-chart
      - name: grok_connect lint
        if: steps.chart_changes.outputs.grok_connect == 'true'
        run: helm lint datagrok_grok_connect
      - name: helm lint h2o
        if: steps.chart_changes.outputs.h2o == 'true'
        run: helm lint datagrok_h2o
      - name: helm lint jkg
        if: steps.chart_changes.outputs.jkg == 'true'
        run: helm lint datagrok_jkg
      - name: helm lint jupyter_notebook
        if: steps.chart_changes.outputs.jn == 'true'
        run: helm lint datagrok_jupyter_notebook       
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          addons: registry,ingress
          cache: false
          driver: docker
        
      