name: Build and Push Helm Charts

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.8.2'

      - name: Install Helm Plugin for Registry
        run: helm plugin install https://github.com/chartmuseum/helm-push.git

#      - name: Authenticate Docker
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ secrets.REGISTRY_URL }}

      - name: Detect Changed Helm Charts
        id: changes
        run: |
          echo "CHANGED_CHARTS=$(git diff --name-only HEAD~1 HEAD | grep 'base/' | cut -d '/' -f 2 | uniq)" >> $GITHUB_ENV
      - name: check changes
        run: echo $CHANGED_CHARTS
#      - name: Build and Push Changed Helm Charts
#        if: env.CHANGED_CHARTS != ''
#        run: |
#          for chart in $CHANGED_CHARTS; do
#            echo "Packaging $chart..."
#            helm package charts/$chart
#            echo "Pushing $chart..."
#            helm cm-push ./$chart-*.tgz ${{ secrets.REGISTRY_URL }}
#          done